### ISSUE TITLE
Flush stdout/stderr

### ISSUE THREAD

**Issue by DavidEGrayson** [midipix-project/slibtool#1]
I mentioned this on IRC, and the midipix project author agreed that I had a valid point:  slibtool should be patched to flush its stdout after printing the command it is going to run.  I was running slibtool in an environment where stderr and stdout were both going to a log file, and I noticed that a linker error message showed up in the middle of the really long linker command printed by slibtool.

**Comment by midipix** [comment]
thanks! fixed in commit 26127d8.
