### ISSUE TITLE
building on Mac (Darwin), and building with a specific compiler (toolchain)

### ISSUE THREAD

**Issue by RJVB** [midipix-project/slibtool#12]
Slibtool could be a very useful tool for building autoconf-based projects (the libtool script can cause significant overhead from the system's gatekeeper daemon) so I'm looking into the possibility to write a MacPorts portfile for it.

I'm running into issues with the custom configure, though. The script terminates with exit code 2 without any error message. Is there a way to get some constructive feedback about whatever goes wrong? My current commandline:

```
../slibtool-src/configure --prefix=/opt/local --disable-dependency-tracking --source-dir=../slibtool-src --host=x86_64-apple-darwin13.4.0 --compiler=clang
```

`--host` is required because otherwise the script will use the hostname (clang doesn't like), the `--compiler` because otherwise the script finds an obsure C99 executable somewhere deep in Xcode and which is clearly not intended to be manhandled.

I see the configure system also attemps to figure out the assembler. MacPorts provides a number of compilers (with distinctive names) and makes it a point to control exactly which compiler and other toolchain components are used for building a project. Is there a way to specify the other required toolchain components?

I presume those components aren't hardcoded, i.e. once built slibtool is toolchain-agnostic?!

**Comment by midipix** [comment]
Funny timing! I was aware of this and actually solved the bug (two of them, in fact: one due to an incorrect sed syntax, the other related to c99) yesterday, just haven't pushed yet. More on that in the next hour or so... and yes, I do intend to add a config.log to sofort (slibtool's own build system), should be able to get to that this weekend.

PS#1. with the aforementioned fixes in place, you will need neither --host nor --compiler (on a related note, --disable-dependency-tracking is recognized by configure but has no effect in sofort, and hence may be omitted as well).

PS#2. once built, slibtool is indeed toolchain agnostic and correctly uses the tools associated with the compiler passed to it via the command line.

**Comment by midipix** [comment]
Fixed in commits 43a2594 (sed syntax) and 1311bb4 (tool compatibility test).

**Comment by midipix** [comment]
Regarding the use slibtool for osx builds: this has been tested quite recently (that is, shortly before the build-system overhaul) and found to be working well as expected. That said, more testing on osx osx is very welcome, and I'm thus glad to see someone looking into that. Should you run into any problems while testing, please try also the #midipix channel on the freenode irc network, as several people in the community know slibtool well enough to be able to provide immediate tips and tricks (or, heavens forbid, confirm an actual bug in slibtool).

**Comment by RJVB** [comment]
Thanks! I'll have a look as soon as I get back to my Mac. I have a "fun" project to test it with - mesa 18.3 though that version no longer seems to build with a simple "fat binary" approach so I'll need another project to test that aspect (where the compiler generates composite binaries that contain entries for multiple architectures; tricky combined with static libraries). Of course, if this shows promise and makes it into an official MacPorts port it could end up seeing a lot of testing in the CI and build bots.

Just one completely unrelated question/suggestion: how do I get rid of the coloured output? I'm not colourblind, but my usual terminal background (#E0F2C8 ... sue me ;)) makes the output from --help almost impossible to read.

**Comment by RJVB** [comment]
>PS#1. with the aforementioned fixes in place, you will need neither --host nor --compiler

I'm still going to want to be able to decide which toolchain (binaries + arguments) to use for building, and preferably without having to dance with symlinks and/or wrapper scripts!

**Comment by RJVB** [comment]
And sadly, even on Linux:

```
> (cd slibtool-src ; git describe)
v0.5.28-79-g1311bb4
> (cd build ; env CC=clang CFLAGS="-Os -g -flto=thin" ../slibtool-src/configure --prefix=/opt/local --source-dir=../slibtool-src)
ccenv:
ccenv: ccenv_host:   Bola 
ccenv: ccenv_cchost: x86_64-linux-gnu 
ccenv:
ccenv: ccenv_host and ccenv_cchost do not match, most likely because:
ccenv: (1) you explicitly set CC (or passed --compiler=...)
ccenv: (2) the selected compiler does not accept --target=...
ccenv: (3) the host reported by -dumpmachine differs from the one you requested.
ccenv:
ccenv: something went wrong, see the command and compiler message below.

cmd: c99 --target=Bola -E -xc - < /dev/null > /dev/null
gcc: error: unrecognized command line option ‘--target=Bola’; did you mean ‘--target-help’?
```

Note the CC and CFLAGS env. variables!

**Comment by RJVB** [comment]
Configure still fails on Mac, at least on OS X 10.9.5 :

- there is no usable c99 executable (the one that is found raises an error on the argument it's called with)
- the aforementioned "exit 2" is because there is no llvm-readelf in the system toolchain.

And something I forgot to mention: the system mktemp executable is BSD, not GNU.

**Comment by midipix** [comment]
Will look into that, might be easier to solve once I have access to an OS X 10.9.5 machine, or otherwise we can do the debugging together on irc.

**Comment by RJVB** [comment]
I'm not very often on IRC but we could make an appointment at some point...

Am I right that the failing step is just to confirm the nature of the produced binary? If so you could probably add a fallback that uses the `file` utility. Or else use `otool -h`. 

```
> otool -h 64bit.binary
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777223          3  0x80           2    19       1552 0x00200085

> otool -h 32bit.binary
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedface       7          3  0x00           2    20       1672 0x01000085

> otool -h elf.binary
llvm-objdump: 'elf.binary': Object is not a Mach-O file type.

```

**Comment by midipix** [comment]
> ccenv: ccenv_host: Bola

Does Bola come from the HOST environment variable? What/who sets it, and is there a good reason for that...

**Comment by midipix** [comment]
> Mach header magic cputype cpusubtype caps filetype ncmds sizeofcmds flags 0xfeedfacf 16777223 3 0x80 2 19 1552 0x00200085

> Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedface       7          3  0x00           2    20       1672 0x01000085

Would you mind pasting here the output of `hexdump -C a.out | head` ran on both files (64- & 32-bit)? The Mach-O detection logic has thus far only been tested on two osx machines, where it did work as expected, so I suspect the problem has something to do with an oversight concerning one or the other variant.

**Comment by RJVB** [comment]
>Does Bola come from the HOST environment variable? What/who sets it, and is there a good reason for that...

It does. Setting it to the host name is traditional UNIX behaviour, no? It's used throughout login/setup scripts I've been using since the early nineties...
OTOH, I've never seen it used to determine the autoconf-style --host triplet (never interfered with that, either)

> so I suspect the problem has something to do with an oversight concerning one or the other variant.

No, the problem is really simply one of not finding the appropriate tool (and lack of a proper error message for *that* ;)). Once I hard-coded the path to one of my MacPorts llvm-readelf versions the configure step completed successfully.

FWIW, otool does seem to call llvm-objdump in the background (or else it includes part of that tool's code and unchanged error messages).

**Comment by midipix** [comment]
Will look into both of the above later today. In the meantime, and assuming you do not mind, I would still like to have the output of `hexdump -C a.out | head` ran on both Mach-O files (64- & 32-bit). Thanks for following up!

**Comment by RJVB** [comment]
The 64-bit exec from above:

```
0000000 cf fa ed fe 07 00 00 01 03 00 00 80 02 00 00 00
0000010 13 00 00 00 10 06 00 00 85 00 20 00 00 00 00 00
0000020 19 00 00 00 48 00 00 00 5f 5f 50 41 47 45 5a 45
0000030 52 4f 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000040 00 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00
0000050 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000060 00 00 00 00 00 00 00 00 19 00 00 00 28 02 00 00
0000070 5f 5f 54 45 58 54 00 00 00 00 00 00 00 00 00 00
0000080 00 00 00 00 01 00 00 00 00 40 00 00 00 00 00 00
0000090 00 00 00 00 00 00 00 00 00 40 00 00 00 00 00 00
```

And the 32-bit one:

```
0000000 ce fa ed fe 07 00 00 00 03 00 00 00 02 00 00 00
0000010 14 00 00 00 88 06 00 00 85 00 00 01 01 00 00 00
0000020 38 00 00 00 5f 5f 50 41 47 45 5a 45 52 4f 00 00
0000030 00 00 00 00 00 00 00 00 00 10 00 00 00 00 00 00
0000040 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000050 00 00 00 00 01 00 00 00 14 02 00 00 5f 5f 54 45
0000060 58 54 00 00 00 00 00 00 00 00 00 00 00 00 f0 7b
0000070 00 20 00 00 00 00 00 00 00 20 00 00 07 00 00 00
0000080 05 00 00 00 07 00 00 00 00 00 00 00 5f 5f 74 65
0000090 78 74 00 00 00 00 00 00 00 00 00 00 5f 5f 54 45
```

And for good measure a 32+64 universal Intel binary:
```
0000000 ca fe ba be 00 00 00 02 01 00 00 07 80 00 00 03
0000010 00 00 10 00 00 09 ea 30 00 00 00 0c 00 00 00 07
0000020 00 00 00 03 00 0a 00 00 00 09 3c 78 00 00 00 0c
0000030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
*
0001000 cf fa ed fe 07 00 00 01 03 00 00 80 02 00 00 00
0001010 12 00 00 00 90 07 00 00 85 00 20 00 00 00 00 00
0001020 19 00 00 00 48 00 00 00 5f 5f 50 41 47 45 5a 45
0001030 52 4f 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0001040 00 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00
```

**Comment by RJVB** [comment]
Just a heads-up, this works just fine for me in ccenv.sh:

```
	# MACHO / file
	if [ -x "/usr/bin/file" ] && [ -z "$ccenv_cc_binfmt" ]; then
		/usr/bin/file -h  $ccenv_image 2>/dev/null       \
			| grep -i "$ccenv_image: Mach-O"            \
				> /dev/null                       \
		&& ccenv_cc_binfmt='MACHO'                        \
		&& ccenv_use_objdump=yes
	fi
```

(as the last Mach-O test in the list)

**Comment by midipix** [comment]
HOST/TARGET environment variables no longer affect configure as per commit 526af0b.

**Comment by midipix** [comment]
When present, otool(1) is now (49f783d) used before any other tool for detection of the Mach-O binary format.

**Comment by midipix** [comment]
I believe that the above two commits resolve everything covered in this issue, and that slibtool should now configure and build out of the box on your version of Darwin; please confirm...

**Comment by RJVB** [comment]
Sadly, no, there's still the issue that the mktemp command is the BSD variant which has an obligatory template. DIdn't I mention that?

```
> configure
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
```

With that fixed the configure step succeeds, but the build still fails on something I think I did NOT yet mention: no AT_FDCWD.
There's a legacy support package in MacPorts which I used to work around that issue, but maybe there's a cleaner way?

**Comment by midipix** [comment]
> And something I forgot to mention: the system mktemp executable is BSD, not GNU.
You did mention that but with no accompanying error output, so was not sure what to make of that of what should be fixed...

**Comment by midipix** [comment]
> With that fixed the configure step succeeds, but the build still fails on something I think I did NOT yet mention: no AT_FDCWD.

That'll have to be handled at the distro (MacPorts) level, specifically since slibtool includes `-std=c99 -D_XOPEN_SOURCE=700` in its CFLAGS and expects AT_FDCWD to be present. In my experience, attempting to "know everything about the world's various systems" and define AT_FDCWD on behalf of systems that do not provide it is a bad idea that never works as desired, hence the suggestion to provide the missing bits from within the MacPorts package.

**Comment by midipix** [comment]
Reading [the OpenBsd manual page for mktemp(1)](https://man.openbsd.org/mktemp.1), I'm still not sure why `ccenv_tmp=$(mktemp)` does not work on Darwin 10.9...

**Comment by midipix** [comment]
Looking further, I see now that unlike OpenBsd (and probably most or all bsd's), Darwin makes the template obligatory.

**Comment by midipix** [comment]
To avoid further surprises, could you verify that the following code succeeds on all OSX versions supported by MacPorts:

`ccenv_tmp=$(mktemp ./XXXXXXXXXXXXXXXX)`

**Comment by RJVB** [comment]
> That'll have to be handled at the distro (MacPorts) level

That's perfectly fine.


> could you verify that the following code succeeds on all OSX versions
> supported by MacPorts:
> 
> `ccenv_tmp=$(mktemp ./XXXXXXXXXXXXXXXX)`

I can't verify all versions, sadly. The template works on my system. What I can tell you however is that GNU mktemp is available in a port, as `gmktemp`. If you prefer we can use that, even through a global search replace in the configure and ccenv.sh scripts.

**Comment by midipix** [comment]
> If you prefer [gmktemp]

On the contrary! mktemp(1) invocations now (513f55d) provide an explicit template, and temporary files are accordingly removed by the script.

**Comment by midipix** [comment]
Closing following the above commit and no further comments.
