### ISSUE TITLE
drop-in libtool replacement and ccache

### ISSUE THREAD

**Issue by RJVB** [midipix-project/slibtool#14]
On of the typical ways of injecting ccache into the build of an autoconf-based project is to set `CC=/path/to/ccache $CC`.

This works for the most part, but fails when creating (shared) libraries.

There's an easy workaround: ccache doesn't do anything during link steps and can thus be omitted from the command.

The quick patch below confirms that:

```
diff --git a/src/driver/slbt_amain.c b/src/driver/slbt_amain.c
index 2e5984976776179801aadc972e8f3a04ddb624dc..19ea002c6540542d5d94c3f657ee196197f90295 100644
--- a/src/driver/slbt_amain.c
+++ b/src/driver/slbt_amain.c
@@ -69,8 +70,11 @@ static void slbt_perform_driver_actions(struct slbt_driver_ctx * dctx)
 	if (dctx->cctx->mode == SLBT_MODE_INSTALL)
 		slbt_exec_install(dctx,0);
 
-	if (dctx->cctx->mode == SLBT_MODE_LINK)
+	if (dctx->cctx->mode == SLBT_MODE_LINK) {
+		extern void slbt_ignore_ccache(struct slbt_driver_ctx *dctx);
+		slbt_ignore_ccache(dctx);
 		slbt_exec_link(dctx,0);
+    }
 
 	if (dctx->cctx->mode == SLBT_MODE_UNINSTALL)
 		slbt_exec_uninstall(dctx,0);
diff --git a/src/logic/slbt_exec_link.c b/src/logic/slbt_exec_link.c
index 0bfe7e0432bdba0405bdd137391688f9d5222db0..648f0e0bbef192a0b879a685f21aa35270cbfd3b 100644
--- a/src/logic/slbt_exec_link.c
+++ b/src/logic/slbt_exec_link.c
@@ -11,6 +11,8 @@
 #include <fcntl.h>
 #include <errno.h>
 #include <sys/stat.h>
+#include <string.h>
+#include <libgen.h>
 
 #include <slibtool/slibtool.h>
 #include "slibtool_spawn_impl.h"
@@ -1894,3 +1903,18 @@ int slbt_exec_link(
 
 	return ret;
 }
+
+void slbt_ignore_ccache(struct slbt_driver_ctx *dctx)
+{
+    volatile char *argv0 = strdup(dctx->cctx->cargv[0]);
+    char *compiler = basename(argv0);
+    if (strcmp(compiler, "ccache") == 0 && dctx->cctx->cargv[1]) {
+        // shift the entire argument array
+        char **args = dctx->cctx->cargv;
+        while (args[1]) {
+            *args = args[1];
+            args++;
+        }
+    }
+    free(argv0);
+}
```

**Comment by midipix** [comment]
Looking at gnu libtool's `func_cc_basename()`, there appear to be several _known_ _wrappers_ in addition to _ccache_, namely _compiler_, _distcc_, and _purify_.

It seems to me, then, that slibtool should cleanly support all of the above at the driver level. I'll add that this weekend as well.

**Comment by RJVB** [comment]
Indeed, I'd forgotten about distcc, the others I have no experience with.

Looking forward to the result!

**Comment by midipix** [comment]
Just to confirm, there should be no problem with always invoking the specified wrapper (ccache, distcc, etc.) even in link and install mode, correct? I'm asking since I'd rather not rely on the specifics of one or the other wrapper, as those might change with time.

**Comment by RJVB** [comment]
On Friday February 15 2019 21:08:41 midipix wrote:
> Just to confirm, there should be no problem with always invoking the specified wrapper (ccache, distcc, etc.) even in link and install mode, correct?

For ccache and distcc: no, not for link mode in any event. I can't imagine you'd use compilers and their potential wrappers to install things though?

**Comment by midipix** [comment]
That is correct, and slibtool performs all of the install steps internally anyway (file-copying via the invocation of cp(1), other operations via direct libc calls). In sum, then, we will invoke the wrapper (when specified) in the compile and link modes, and leave the install mode implementation as is.

**Comment by RJVB** [comment]
About link mode: --whole-archive is unknown on Mac:

```
diff --git a/src/logic/slbt_exec_link.c b/src/logic/slbt_exec_link.c
index 0bfe7e0432bdba0405bdd137391688f9d5222db0..6a2e36f650540a07dd7f616f928007253fde9f15 100644
--- a/src/logic/slbt_exec_link.c
+++ b/src/logic/slbt_exec_link.c
@@ -373,10 +375,18 @@ static int slbt_exec_link_adjust_argument_vector(
 	for (; *carg; ) {
 		dpath = 0;
 
+#ifndef __APPLE__
 		if (!strcmp(*carg,"-Wl,--whole-archive"))
 			fwholearchive = true;
 		else if (!strcmp(*carg,"-Wl,--no-whole-archive"))
 			fwholearchive = false;
+#else
+		// -noall_load is the default
+		if (!strcmp(*carg,"-Wl,-all_load"))
+			fwholearchive = true;
+		else
+			fwholearchive = false;
+#endif
 
 
 
@@ -421,15 +431,24 @@ static int slbt_exec_link_adjust_argument_vector(
 			*aarg++ = *carg++;
 
 		} else if (!(strcmp(dot,".a"))) {
+#ifndef __APPLE__
 			if (flibrary && !fwholearchive)
 				*aarg++ = "-Wl,--whole-archive";
+#else
+			if (flibrary && !fwholearchive)
+				*aarg++ = "-Wl,-all_load";
+#endif
 
 			dpath = lib;
 			sprintf(lib,"%s.slibtool.deps",*carg);
 			*aarg++ = *carg++;
 
+#ifndef __APPLE__
 			if (flibrary && !fwholearchive)
 				*aarg++ = "-Wl,--no-whole-archive";
+#else
+            // -noall_load is obsolete and ignored with a warning
+#endif
 
 		} else if (strcmp(dot,dctx->cctx->settings.dsosuffix)) {
 			*aarg++ = *carg++;
```

**Comment by midipix** [comment]
This cannot be supported by way of an #ifdef for a variety of reasons, most notably the fact that slibtool is commonly used for cross compilation. This can (and soon will) be supported, however, at the driver level, settings the string for all-archive to either '-Wl,--whole-archive' or '-Wl,-all_load' depending on the target. Please confirm that all_load is indeed prefixed by only one dash.

**Comment by midipix** [comment]
> // -noall_load is obsolete and ignored with a warning

does that mean that -all_load only affects the input argument following it? I am asking since --whole-archive affects not only the following, but also all subsequent input arguments, hence the need for --no-whole-archive.

**Comment by RJVB** [comment]
Note that I mostly just show the patches that point out issues and address them for me. Otherwise I'd end up doing PRs ;)

Yes, there's only a single dash to -all_load

>does that mean that -all_load only affects the input argument following it? I am asking since --whole-archive affects not only the following, but also all subsequent input arguments, hence the need for --no-whole-archive.

See this: https://stackoverflow.com/questions/2906147/what-does-the-all-load-linker-flag-do; from the technote cited in that discussion:

> The workaround is to use the -all_load or -force_load flags. -all_load
> forces the linker to load all object files from every archive it sees, even
> those without Objective-C code. -force_load is available in Xcode 3.2 and
> later. It allows finer grain control of archive loading. Each -force_load
> option must be followed by a path to an archive, and every object file in
> that archive will be loaded.

(I didn't know this, TBH, I've only ever used the all_load option in rare, manual situations.)

**Comment by midipix** [comment]
Does OSX 10.9.5 (which people tell me is rather ancient...) have Xcode 3.2 or later? If so, then -force_load should be the switch to use when targeting mach-o.

**Comment by RJVB** [comment]
Xcode 6.2

10.9 isn't very recent indeed, but I wouldn't call it ancient just yet.

Ancient would be 10.7 or what runs on PPC Macs - and those are still supported in MacPorts ;)

About the parsing of actual libtool scripts: do you also obtain the AR_FLAGS from there? I've been seeing some errors raised by the Mac system ar command, including a rather recent version.


```
> ar -M
usage:  ar -d [-TLsv] archive file ...
        ar -m [-TLsv] archive file ...
        ar -m [-abiTLsv] position archive file ...
        ar -p [-TLsv] archive [file ...]
        ar -q [-cTLsv] archive file ...
        ar -r [-cuTLsv] archive file ...
        ar -r [-abciuTLsv] position archive file ...
        ar -t [-TLsv] archive [file ...]
        ar -x [-ouTLsv] archive [file ...]
Exit 1
```

**Comment by midipix** [comment]
As of commit 34988f8, slibtool supports arbitrary compiler wrappers via --ccwrap <wrapper>, as well as the so-called _known_ wrappers with no preceding switch, as supported by gnu libtool.

**Comment by RJVB** [comment]
Great, will test soon!

**Comment by midipix** [comment]
Closing following the above commit and no further comments.

**Comment by RJVB** [comment]
Sorry, I have gotten side-tracked, I'd been telling myself to get back to testing slibtool but it'll be a few more days, probably... :-/

**Comment by midipix** [comment]
No worries; this has been tested on three different systems now and all appeared to go well. While the change itself is system-agnostic, it would still be great if you could get to test that and report back. Thanks!
