### ISSUE TITLE
-dlopen flag not supported

### ISSUE THREAD

**Issue by doughdemon** [midipix-project/slibtool#6]
It would suffice for me to make it a nop that takes one argument. (The libtool manual says that it is a nop in many situations.)

fontforge uses that flag. It creates a plugin `gb12345.so`, and later links something with `-dlopen gb12345.la`. This currently causes slibtool to pass `-l2345` to the linker...

I've tried adding the flag to `slbt_default_options` but that does not seem to suffice. (*.la files get removed from the command line before the flags are parsed?)

**Comment by midipix** [comment]
thanks for reporting the fontforge dependency; -dlopen support (driver-only at the moment) added in commit 05ca7ea5.

**Comment by doughdemon** [comment]
Thanks!
