### ISSUE TITLE
Implement --disable-static

### ISSUE THREAD

**Issue by doughdemon** [midipix-project/slibtool#7]
Currently, `--disable-static` is a no-op.

**Comment by midipix** [comment]
fair enough; --disable-static actually is supported at the driver level (git grep DISABLE_STATIC src/driver), however the corresponding driver flag is not being regarded anywhere.

can you confirm that within slibtool, --disable-static should mean <<generarte libfoo.so but not libfoo.a, and also generate .libs/foo.lo but not .libs/foo.o>>?

**Comment by doughdemon** [comment]
> can you confirm that within slibtool, --disable-static should mean
> <<generarte libfoo.so but not libfoo.a, and also generate
> .libs/foo.lo but not .libs/foo.o>>?

I can confirm that GNU libtool does so, and don't see any reason to do
something else. (Personally, I am mostly interested in libfoo.a not
getting installed.)

**Comment by midipix** [comment]
thanks for confirming; and yes, the installation is another important aspect of that. will do.

**Comment by doughdemon** [comment]
Thanks!

**Comment by midipix** [comment]
-disable-static is now respected in compile mode (via the driver), link mode, and install mode; see commits 252629e, 1753628, and 005b656, respectively. If anything does not work as expected please let me know!

**Comment by doughdemon** [comment]
Seems to work well. Thanks!
