### ISSUE TITLE
slibtool filters out --target from compile/link flags

### ISSUE THREAD

**Issue by michaelforney** [midipix-project/slibtool#9]
clang uses the `--target` flag to specify a cross-compilation target. However, it also looks like slibtool handles `--target` specially, with the help text `set an explicit (cross-)target, then pass it to the compiler`. 

What does slibtool do with this option? I don't see the target being passed to the compiler.

**Comment by midipix** [comment]
The observation is correct. Currently, slibtool does indeed "set an explicit (cross-)target", but then does not "pass it to the compiler".

I should be able to fix this within the next three days, and will try to attend to this even earlier.

**Comment by midipix** [comment]
It seems to me that a good approach would be the following:

* for a --target argument that precedes the compiler argument, as in: slibtool --target=xxx --mode=compile cc
--> set an explicit (cross-)target,
--> but do not pass the argument to the compiler.

* for a --target argument that follows the compiler argument, as in: slibtool --mode=compile cc --target=xxx
--> set an explicit (cross-)target,
--> and also pass the argument to the compiler.

Please let me know how that sounds.

**Comment by michaelforney** [comment]
Yeah, that sounds reasonable to me.

**Comment by midipix** [comment]
Thanks for identifying the issue. Fixed according to the above in commit 288d628.

**Comment by midipix** [comment]
Fixed in commit 288d628, reported on irc by multiple users to be working.
